import Lean

namespace ChoirUnion.Authority

/-- ReplayWitness is portable metadata about a declaration's properties.
    It is obtained by introspection of the local Lean environment or external replay.
    A deserialized witness is still a claim, not independent verification.
    Only local environment inspection or a trusted replay process can generate authoritative evidence.
--/
structure ReplayWitness where
  /-- Whether the declaration was found in the inspected environment. --/
  declarationFound : Bool
  /-- Whether the declaration is a theorem (not def, opaque, axiom, etc.). --/
  isTheorem : Bool
  /-- Count of transitive sorry/sorryAx uses in the declaration. --/
  sorryCount : Nat
  /-- List of axiom names used by the declaration, as Lean.Name.
      Never serialize/deserialize through strings; Lean.Name structure is part of the identity.
  --/
  usedAxioms : List Lean.Name
  deriving Repr, DecidableEq

/-- clean is a pure syntactic predicate: the witness data is internally consistent
    with the supplied allowed axiom list.
    
    clean(w, A) ⟹ w is structurally valid relative to A
    
    clean(w, A) does NOT establish:
    - that w was independently generated by Lean's kernel
    - that the usedAxioms list was obtained from an actual compilation
    - that sorryCount is an accurate count
    
    Those assurances must come from:
    - local environment inspection via CoreM and Lean metaprogramming
    - external replay via an independent checker like lean4checker
    - cryptographic signatures binding the witness to a trusted builder
    
    A deserialized or untrusted witness passing clean() is still not evidence
    until re-verified in a trusted environment.
--/
def clean (w : ReplayWitness) (allowedAxioms : List Lean.Name) : Bool :=
  w.declarationFound &&
  w.isTheorem &&
  w.sorryCount == 0 &&
  w.usedAxioms.all (fun ax => allowedAxioms.contains ax)

/-- Specification theorem: if clean returns true, then the witness satisfies
    all the structural conditions. This is a pure logical equivalence and does
    not claim external verification.
--/
theorem clean_spec (w : ReplayWitness) (allowedAxioms : List Lean.Name) :
    clean w allowedAxioms = true ↔
      w.declarationFound ∧
      w.isTheorem ∧
      w.sorryCount = 0 ∧
      (∀ ax ∈ w.usedAxioms, allowedAxioms.contains ax) := by
  unfold clean
  constructor
  · intro h
    simp at h
    exact h
  · intro h
    rcases h with ⟨hFound, hTheorem, hs0, hAllowed⟩
    simp [hFound, hTheorem, hs0, hAllowed]

end ChoirUnion.Authority
